# Generated by Django 4.1.4 on 2022-12-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='id',
        ),
        migrations.AddField(
            model_name='tutor',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tutor',
            name='subject_experties',
            field=models.CharField(default='Math', max_length=100),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tutor_id',
            field=models.AutoField(default='Maths', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutor',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
