# Generated by Django 4.1.4 on 2022-12-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_tutor_contact_number_remove_tutor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='subject_experties',
            field=models.CharField(default='', max_length=100),
        ),
    ]
