# Generated by Django 4.1.4 on 2023-01-14 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_student_user_alter_tutor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default name', max_length=100)),
                ('email', models.EmailField(default='default email', max_length=254)),
                ('subject_required', models.CharField(default='default subject', max_length=100)),
                ('contact_number', models.CharField(default='0000000000', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='TutorReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default name', max_length=255)),
                ('email', models.EmailField(default='default email', max_length=255)),
                ('subject_experties', models.CharField(default='default subject', max_length=100)),
                ('bio', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='user',
        ),
        migrations.AlterField(
            model_name='application',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.tutorreg'),
        ),
        migrations.AlterField(
            model_name='job',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.studentreg'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
