# Generated by Django 4.1.4 on 2023-01-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='student',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
