# Generated by Django 4.1.4 on 2023-01-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_submit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submit',
        ),
    ]
