# Generated by Django 4.1.4 on 2023-01-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_resgistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resgistration',
        ),
        migrations.AddField(
            model_name='student',
            name='subject_required',
            field=models.CharField(default='Math', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact_number',
            field=models.CharField(max_length=13),
        ),
    ]
