# Generated by Django 4.1.4 on 2023-01-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_delete_resgistration_student_subject_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subject_required',
            field=models.CharField(max_length=100),
        ),
    ]
