# Generated by Django 4.1.4 on 2023-01-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_student_subject_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subject_required',
            field=models.CharField(max_length=100),
        ),
    ]
